[0m00:21:27.572395 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcf7752a2c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcf7530f400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcf7530f3a0>]}


============================== 00:21:27.574881 | c2e3fdf6-776e-4497-ae3f-966888094764 ==============================
[0m00:21:27.574881 [info ] [MainThread]: Running with dbt=1.7.13
[0m00:21:27.575634 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/home/minh/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt init customer_online_transactions_analytics', 'send_anonymous_usage_stats': 'True'}
[0m00:21:27.576490 [debug] [MainThread]: Starter project path: /home/minh/anaconda3/envs/cota_dbt/lib/python3.10/site-packages/dbt/include/starter_project
[0m00:21:27.578376 [info ] [MainThread]: 
Your new dbt project "customer_online_transactions_analytics" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m00:21:27.578918 [info ] [MainThread]: Setting up your profile.
[0m00:21:35.863914 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 8.334018, "process_user_time": 2.050943, "process_kernel_time": 0.09595, "process_mem_max_rss": "98788", "process_in_blocks": "4160", "process_out_blocks": "72"}
[0m00:21:35.864717 [debug] [MainThread]: Command `dbt init` succeeded at 00:21:35.864383 after 8.33 seconds
[0m00:21:35.865336 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcf7752a2c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcf7530f130>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcf7530f580>]}
[0m00:21:35.865839 [debug] [MainThread]: Flushing usage events
[0m00:31:36.616665 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3ad291e2f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3ad0703400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3ad07033a0>]}


============================== 00:31:36.619235 | 009416be-bee3-42b1-9dbb-8be2b6575182 ==============================
[0m00:31:36.619235 [info ] [MainThread]: Running with dbt=1.7.13
[0m00:31:36.620200 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/minh/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt debug', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:31:36.620933 [info ] [MainThread]: dbt version: 1.7.13
[0m00:31:36.621584 [info ] [MainThread]: python version: 3.10.0
[0m00:31:36.622252 [info ] [MainThread]: python path: /home/minh/anaconda3/envs/cota_dbt/bin/python3.10
[0m00:31:36.622673 [info ] [MainThread]: os info: Linux-5.19.0-32-generic-x86_64-with-glibc2.35
[0m00:31:36.627579 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.sqlite'
[0m00:31:36.853971 [info ] [MainThread]: Using profiles dir at /home/minh/.dbt
[0m00:31:36.857202 [info ] [MainThread]: Using profiles.yml file at /home/minh/.dbt/profiles.yml
[0m00:31:36.858600 [info ] [MainThread]: Using dbt_project.yml file at /home/minh/khoidata/GitHub/customer_online_transactions_analytics/dbt_project.yml
[0m00:31:36.860085 [info ] [MainThread]: Configuration:
[0m00:31:36.861734 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m00:31:36.863207 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m00:31:36.864879 [info ] [MainThread]: Required dependencies:
[0m00:31:36.866720 [debug] [MainThread]: Executing "git --help"
[0m00:31:36.875435 [debug] [MainThread]: STDOUT: "b"usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m00:31:36.877549 [debug] [MainThread]: STDERR: "b''"
[0m00:31:36.879417 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m00:31:36.881137 [info ] [MainThread]: Connection test skipped since no profile was found
[0m00:31:36.882036 [info ] [MainThread]: [31m2 checks failed:[0m
[0m00:31:36.883089 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "employees_analytics", target "dev" invalid: Runtime Error
    Could not find adapter type sqlite!


[0m00:31:36.883878 [info ] [MainThread]: Project loading failed for the following reason:
 project path </home/minh/khoidata/GitHub/customer_online_transactions_analytics/dbt_project.yml> not found

[0m00:31:36.885980 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.30944252, "process_user_time": 2.194841, "process_kernel_time": 0.083955, "process_mem_max_rss": "99636", "process_in_blocks": "112", "process_out_blocks": "24", "command_success": false}
[0m00:31:36.887709 [debug] [MainThread]: Command `dbt debug` failed at 00:31:36.887306 after 0.31 seconds
[0m00:31:36.888948 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3ad291e2f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3ad0703550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3ad069be80>]}
[0m00:31:36.890138 [debug] [MainThread]: Flushing usage events
[0m00:31:45.487684 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7141122350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f713ef07490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f713ef07430>]}


============================== 00:31:45.490145 | 795b4a02-a229-4f93-a6c0-8512de21112b ==============================
[0m00:31:45.490145 [info ] [MainThread]: Running with dbt=1.7.13
[0m00:31:45.491000 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/home/minh/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:31:45.491603 [info ] [MainThread]: dbt version: 1.7.13
[0m00:31:45.492252 [info ] [MainThread]: python version: 3.10.0
[0m00:31:45.492817 [info ] [MainThread]: python path: /home/minh/anaconda3/envs/cota_dbt/bin/python3.10
[0m00:31:45.493567 [info ] [MainThread]: os info: Linux-5.19.0-32-generic-x86_64-with-glibc2.35
[0m00:31:45.498543 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.sqlite'
[0m00:31:45.714346 [info ] [MainThread]: Using profiles dir at /home/minh/.dbt
[0m00:31:45.716430 [info ] [MainThread]: Using profiles.yml file at /home/minh/.dbt/profiles.yml
[0m00:31:45.717433 [info ] [MainThread]: Using dbt_project.yml file at /home/minh/khoidata/GitHub/customer_online_transactions_analytics/dbt_project.yml
[0m00:31:45.718243 [info ] [MainThread]: Configuration:
[0m00:31:45.719033 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m00:31:45.719746 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m00:31:45.720448 [info ] [MainThread]: Required dependencies:
[0m00:31:45.721464 [debug] [MainThread]: Executing "git --help"
[0m00:31:45.726536 [debug] [MainThread]: STDOUT: "b"usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m00:31:45.728189 [debug] [MainThread]: STDERR: "b''"
[0m00:31:45.728994 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m00:31:45.729902 [info ] [MainThread]: Connection test skipped since no profile was found
[0m00:31:45.730875 [info ] [MainThread]: [31m2 checks failed:[0m
[0m00:31:45.731664 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "employees_analytics", target "dev" invalid: Runtime Error
    Could not find adapter type sqlite!


[0m00:31:45.732668 [info ] [MainThread]: Project loading failed for the following reason:
 project path </home/minh/khoidata/GitHub/customer_online_transactions_analytics/dbt_project.yml> not found

[0m00:31:45.735738 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.28831753, "process_user_time": 2.265136, "process_kernel_time": 0.06003, "process_mem_max_rss": "99584", "process_out_blocks": "16", "command_success": false, "process_in_blocks": "0"}
[0m00:31:45.738198 [debug] [MainThread]: Command `dbt debug` failed at 00:31:45.737697 after 0.29 seconds
[0m00:31:45.738984 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7141122350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f713ef07700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f713ee9af80>]}
[0m00:31:45.740492 [debug] [MainThread]: Flushing usage events
[0m00:34:09.667827 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe4b55163b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe4b33034f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe4b3303490>]}


============================== 00:34:09.670437 | 3b633c84-ea59-4510-89ea-88a6ae327486 ==============================
[0m00:34:09.670437 [info ] [MainThread]: Running with dbt=1.7.13
[0m00:34:09.671350 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/minh/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:34:09.672060 [info ] [MainThread]: dbt version: 1.7.13
[0m00:34:09.672714 [info ] [MainThread]: python version: 3.10.0
[0m00:34:09.673345 [info ] [MainThread]: python path: /home/minh/anaconda3/envs/cota_dbt/bin/python3.10
[0m00:34:09.673716 [info ] [MainThread]: os info: Linux-5.19.0-32-generic-x86_64-with-glibc2.35
[0m00:34:09.679042 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.sqlite'
[0m00:34:09.818730 [info ] [MainThread]: Using profiles dir at /home/minh/.dbt
[0m00:34:09.819457 [info ] [MainThread]: Using profiles.yml file at /home/minh/.dbt/profiles.yml
[0m00:34:09.820069 [info ] [MainThread]: Using dbt_project.yml file at /home/minh/khoidata/GitHub/customer_online_transactions_analytics/dbt_project.yml
[0m00:34:09.820527 [info ] [MainThread]: Configuration:
[0m00:34:09.821034 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m00:34:09.821491 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m00:34:09.821928 [info ] [MainThread]: Required dependencies:
[0m00:34:09.822393 [debug] [MainThread]: Executing "git --help"
[0m00:34:09.824045 [debug] [MainThread]: STDOUT: "b"usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m00:34:09.824560 [debug] [MainThread]: STDERR: "b''"
[0m00:34:09.825282 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m00:34:09.826017 [info ] [MainThread]: Connection test skipped since no profile was found
[0m00:34:09.826658 [info ] [MainThread]: [31m2 checks failed:[0m
[0m00:34:09.827315 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "employees_analytics", target "dev" invalid: Runtime Error
    Could not find adapter type sqlite!


[0m00:34:09.827903 [info ] [MainThread]: Project loading failed for the following reason:
 project path </home/minh/khoidata/GitHub/customer_online_transactions_analytics/dbt_project.yml> not found

[0m00:34:09.828911 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.20789126, "process_user_time": 2.248749, "process_kernel_time": 0.084028, "process_mem_max_rss": "99560", "process_out_blocks": "24", "command_success": false, "process_in_blocks": "0"}
[0m00:34:09.829502 [debug] [MainThread]: Command `dbt debug` failed at 00:34:09.829310 after 0.21 seconds
[0m00:34:09.830026 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe4b55163b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe4b3303760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe4b32968c0>]}
[0m00:34:09.830612 [debug] [MainThread]: Flushing usage events
[0m00:35:40.869471 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f92c9922380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f92c72e34f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f92c72e3490>]}


============================== 00:35:40.872152 | a0f49094-22a5-4667-85fe-f5649b378505 ==============================
[0m00:35:40.872152 [info ] [MainThread]: Running with dbt=1.7.13
[0m00:35:40.872953 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/home/minh/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt debug', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m00:35:40.873535 [info ] [MainThread]: dbt version: 1.7.13
[0m00:35:40.874051 [info ] [MainThread]: python version: 3.10.0
[0m00:35:40.874603 [info ] [MainThread]: python path: /home/minh/anaconda3/envs/cota_dbt/bin/python3.10
[0m00:35:40.875129 [info ] [MainThread]: os info: Linux-5.19.0-32-generic-x86_64-with-glibc2.35
[0m00:35:40.881052 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.sqlite'
[0m00:35:41.032382 [info ] [MainThread]: Using profiles dir at /home/minh/.dbt
[0m00:35:41.033182 [info ] [MainThread]: Using profiles.yml file at /home/minh/.dbt/profiles.yml
[0m00:35:41.033773 [info ] [MainThread]: Using dbt_project.yml file at /home/minh/khoidata/GitHub/customer_online_transactions_analytics/dbt_project.yml
[0m00:35:41.034426 [info ] [MainThread]: Configuration:
[0m00:35:41.035047 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m00:35:41.035653 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m00:35:41.036187 [info ] [MainThread]: Required dependencies:
[0m00:35:41.036842 [debug] [MainThread]: Executing "git --help"
[0m00:35:41.039251 [debug] [MainThread]: STDOUT: "b"usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m00:35:41.040163 [debug] [MainThread]: STDERR: "b''"
[0m00:35:41.040880 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m00:35:41.041538 [info ] [MainThread]: Connection test skipped since no profile was found
[0m00:35:41.042204 [info ] [MainThread]: [31m2 checks failed:[0m
[0m00:35:41.042852 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "employees_analytics", target "dev" invalid: Runtime Error
    Could not find adapter type sqlite!


[0m00:35:41.043630 [info ] [MainThread]: Project loading failed for the following reason:
 project path </home/minh/khoidata/GitHub/customer_online_transactions_analytics/dbt_project.yml> not found

[0m00:35:41.044915 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.21815354, "process_user_time": 2.224475, "process_kernel_time": 0.068014, "process_mem_max_rss": "99708", "process_out_blocks": "16", "command_success": false, "process_in_blocks": "0"}
[0m00:35:41.045986 [debug] [MainThread]: Command `dbt debug` failed at 00:35:41.045654 after 0.22 seconds
[0m00:35:41.047910 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f92c9922380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f92c72e3760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f92c7277970>]}
[0m00:35:41.049940 [debug] [MainThread]: Flushing usage events
[0m00:37:01.380164 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa7fc826380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa7fa6134f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa7fa613490>]}


============================== 00:37:01.382868 | ee4fa9b6-ab67-4119-8d5a-b2ffa2d50b09 ==============================
[0m00:37:01.382868 [info ] [MainThread]: Running with dbt=1.7.13
[0m00:37:01.383573 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/minh/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:37:01.384177 [info ] [MainThread]: dbt version: 1.7.13
[0m00:37:01.384675 [info ] [MainThread]: python version: 3.10.0
[0m00:37:01.385154 [info ] [MainThread]: python path: /home/minh/anaconda3/envs/cota_dbt/bin/python3.10
[0m00:37:01.385603 [info ] [MainThread]: os info: Linux-5.19.0-32-generic-x86_64-with-glibc2.35
[0m00:37:01.513078 [info ] [MainThread]: Using profiles dir at /home/minh/.dbt
[0m00:37:01.513739 [info ] [MainThread]: Using profiles.yml file at /home/minh/.dbt/profiles.yml
[0m00:37:01.514366 [info ] [MainThread]: Using dbt_project.yml file at /home/minh/khoidata/GitHub/customer_online_transactions_analytics/dbt_project.yml
[0m00:37:01.515010 [info ] [MainThread]: adapter type: mysql
[0m00:37:01.515583 [info ] [MainThread]: adapter version: 1.7.0
[0m00:37:01.516354 [info ] [MainThread]: Configuration:
[0m00:37:01.517200 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m00:37:01.517853 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m00:37:01.518388 [info ] [MainThread]: Required dependencies:
[0m00:37:01.519375 [debug] [MainThread]: Executing "git --help"
[0m00:37:01.521211 [debug] [MainThread]: STDOUT: "b"usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m00:37:01.521673 [debug] [MainThread]: STDERR: "b''"
[0m00:37:01.522052 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m00:37:01.522514 [info ] [MainThread]: Connection:
[0m00:37:01.523093 [info ] [MainThread]:   server: localhost
[0m00:37:01.523834 [info ] [MainThread]:   unix_socket: None
[0m00:37:01.524309 [info ] [MainThread]:   port: 3306
[0m00:37:01.524987 [info ] [MainThread]:   database: None
[0m00:37:01.525652 [info ] [MainThread]:   schema: data_study
[0m00:37:01.526332 [info ] [MainThread]:   user: admin
[0m00:37:01.527119 [info ] [MainThread]: Registered adapter: mysql=1.7.0
[0m00:37:01.528032 [debug] [MainThread]: Acquiring new mysql connection 'debug'
[0m00:37:01.528742 [debug] [MainThread]: Using mysql connection "debug"
[0m00:37:01.529371 [debug] [MainThread]: On debug: select 1 as id
[0m00:37:01.530122 [debug] [MainThread]: Opening a new connection, currently in state init
[0m00:37:01.563999 [debug] [MainThread]: SQL status: SUCCESS 1 in 0.0 seconds
[0m00:37:01.566379 [debug] [MainThread]: On debug: Close
[0m00:37:01.568801 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m00:37:01.570592 [info ] [MainThread]: [31m1 check failed:[0m
[0m00:37:01.571666 [info ] [MainThread]: Project loading failed for the following reason:
 project path </home/minh/khoidata/GitHub/customer_online_transactions_analytics/dbt_project.yml> not found

[0m00:37:01.573804 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.2346555, "process_user_time": 2.247182, "process_kernel_time": 0.067975, "process_mem_max_rss": "104580", "process_in_blocks": "32", "process_out_blocks": "32", "command_success": false}
[0m00:37:01.575849 [debug] [MainThread]: Command `dbt debug` failed at 00:37:01.575263 after 0.24 seconds
[0m00:37:01.577755 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m00:37:01.578963 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa7fc826380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa7fa5a7850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa7fa3dbcd0>]}
[0m00:37:01.580170 [debug] [MainThread]: Flushing usage events
